### ISSUE TITLE
My pc

### ISSUE THREAD

**Issue by TTR-maniac** [D34DlyKK/ransomeware#1]
HELLO THANK YOU FOR BREAKING MY LAST PC I DONT KNOW WHAT A RANSOMWARE IS BUT IT DOES NOT SOUND FUN
THIS IS NOT A JOKE

**Comment by TTR-maniac** [comment]
![maxresdefault](https://user-images.githubusercontent.com/76447994/104390646-2d206b80-550c-11eb-9266-3eef5a5b94e3.jpg)
THAT IS YOU

**Comment by D34DlyKK** [comment]
This ransomware was just made for educational purposes.
